<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Favicon -->
  <link rel="apple-touch-icon" sizes="57x57" href="/assets/images/favicons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/assets/images/favicons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/assets/images/favicons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/assets/images/favicons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/assets/images/favicons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/assets/images/favicons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/assets/images/favicons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/assets/images/favicons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/assets/images/favicons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/assets/images/favicons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/images/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/assets/images/favicons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicons/favicon-16x16.png">
<link rel="manifest" href="/assets/images/favicons/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/assets/images/favicons/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">


  <!-- Meta information -->
  <title>Python exceptions considered an anti-pattern</title>
  <meta name="description"
        content="">
  <link rel="canonical"
        href="http://localhost:4000/2019/02/python-exceptions-considered-an-antipattern" />

  <!-- Open search scheme -->
  <link rel="search"
        type="application/opensearchdescription+xml"
        title="sobolevn.me"
        href="/opensearch.xml" />

  <!-- Feed -->
  <link rel="alternate" type="application/rss+xml" title="rishi raj's blog"
        href="/feed.xml" />

  <!-- Custom fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,900|Roboto+Mono:400,400i|Montserrat:400,800" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

  <!-- Custom style -->
  <link rel="stylesheet" href="/css/main.css" />

  <!-- Global site tag (gtag.js) - Google Ads: 839642990 -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=AW-839642990"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'AW-839642990');
  </script>
</head>


  <body>
    <main class="u-container">
      <div class="c-page">
  <header class="c-page__header">
  <h1><code>rishi raj's blog</code></h1>

  

  <nav role="navigation">
    <a href="/" role="menuitem">
      Blog
    </a>

    <span class="u-separate"></span>
    <a href="/talks/" role="menuitem">
      Talks
    </a>

    <span class="u-separate"></span>
    <a href="/activities/" role="menuitem">
      Activities
    </a>

    <span class="u-separate"></span>
    <a href="/about/" role="menuitem">
      About
    </a>

    <span class="u-separate"></span>
    <a href="/subscribe/" role="menuitem">
      Subscribe
    </a>
  </nav>
</header>

  <div class="c-page__main">
    <article class="c-article" itemscope="" itemtype="http://schema.org/BlogPosting">
  <header class="c-article__header">
    <h1 class="c-article__title" itemprop="name">Python exceptions considered an anti-pattern</h1>
    <p class="c-article__time">
      <small>
        <time datetime="2019-02-09T00:00:00+05:30" itemprop="datePublished">
          February 9, 2019
        </time>
      </small>
      <small><span class="reading-time" title="Estimated read time">
  
  
    18 mins
   read
</span>
</small>
      <small><a href="#discussion">Start a discussion</a></small>
      <small><a href="https://github.com/sobolevn/sobolevn.github.io/blob/master/_posts/2019-02-09-python-exceptions-considered-an-antipattern.md">Edit this page</a></small>
    </p>
  </header>

  <!-- Post Tags -->
  <!-- <ul class="c-tags">
    
    <li class="c-tag">python</li>
    
  </ul> -->

  <!-- Content -->
  <div class="c-article__main">

    
      
      
      <div class="post-translate">
        <h4>Translated to:</h4>
        <ul>
        
          <li>
            <a class="c-article__repost" href="https://habr.com/ru/company/oleg-bunin/blog/445234/" target="_blank">
              Russian <img class="emoji" title=":ru:" alt=":ru:" src="https://github.githubassets.com/images/icons/emoji/unicode/1f1f7-1f1fa.png" height="20" width="20">
            </a>
            
          </li>
        
        </ul>
      </div>
      
    

    <div class="c-article__body" itemprop="articleBody">
      <p><img src="https://thepracticaldev.s3.amazonaws.com/i/hikrr2fhv3os6b816n3w.png" alt="Article logo"></p>

<p>What are exceptions? Judging by their name it is an entity representing some exceptional situation that happens inside your program.</p>

<p>You might be wondering how do exceptions are an anti-pattern and how does this relate to typing at all? Well, let’s find out!</p>


      <h2 id="problems-with-exceptions">
        
        <a class="anchor" href="#problems-with-exceptions">Problems with exceptions</a>
        
      </h2>

<p>First, we have to prove that exceptions have drawbacks. Well, it is usually hard to find “issues” in things you use every day because they start to look like “features” to you at some point.</p>

<p>Let’s have a fresh look.</p>


    
      <h3 id="exceptions-are-hard-to-notice">
        
        <a class="anchor" href="#exceptions-are-hard-to-notice">Exceptions are hard to notice</a>
        
      </h3>

<p>There are two types of exceptions: “explicit” that are created with <code class="language-plaintext highlighter-rouge">raise</code> keyword right inside the code you are reading and “wrapped” that are wrapped inside some other functions/classes/methods that you are using.</p>

<p>The problem is: it is really hard to notice all this “wrapped” exceptions.
I will illustrate my point with this pure function:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">first</span><span class="p">:</span> <span class="nb">float</span><span class="p">,</span> <span class="n">second</span><span class="p">:</span> <span class="nb">float</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="nb">float</span><span class="p">:</span>
     <span class="k">return</span> <span class="n">first</span> <span class="o">/</span> <span class="n">second</span>
</code></pre></div></div>

<p>All it does is dividing two numbers. Always returning <code class="language-plaintext highlighter-rouge">float</code>. It is type safe and can be used like so:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">result</span> <span class="o">=</span> <span class="n">divide</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="s">'x / y = '</span><span class="p">,</span> <span class="n">result</span><span class="p">)</span>
</code></pre></div></div>

<p>Wait, did you get it? <code class="language-plaintext highlighter-rouge">print</code> will never be actually executed. Because <code class="language-plaintext highlighter-rouge">1 / 0</code> is an impossible operation and <code class="language-plaintext highlighter-rouge">ZeroDivisionError</code> will be raised. So, despite your code is type safe it is not safe to be used.</p>

<p>You still need to have a solid experience to spot these potential problems in a perfectly readable and typed code. Almost everything in <code class="language-plaintext highlighter-rouge">python</code> can fail with different types of exceptions: division, function calls, <code class="language-plaintext highlighter-rouge">int</code>, <code class="language-plaintext highlighter-rouge">str</code>, generators, iterables in <code class="language-plaintext highlighter-rouge">for</code> loops, attribute access, key access, even <code class="language-plaintext highlighter-rouge">raise something()</code> itself may fail. I am not even covering IO operations here. And <a href="https://github.com/python/typing/issues/71">checked exceptions won’t be supported</a> in the nearest future.</p>


    
      <h3 id="restoring-normal-behavior-in-place-is-impossible">
        
        <a class="anchor" href="#restoring-normal-behavior-in-place-is-impossible">Restoring normal behavior in-place is impossible</a>
        
      </h3>

<p>Hey, but we always have <code class="language-plaintext highlighter-rouge">except</code> cases just for this kind of situations. Let’s just handle <code class="language-plaintext highlighter-rouge">ZeroDivisionError</code> and we will be safe!</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">first</span><span class="p">:</span> <span class="nb">float</span><span class="p">,</span> <span class="n">second</span><span class="p">:</span> <span class="nb">float</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="nb">float</span><span class="p">:</span>
     <span class="k">try</span><span class="p">:</span>
         <span class="k">return</span> <span class="n">first</span> <span class="o">/</span> <span class="n">second</span>
     <span class="k">except</span> <span class="nb">ZeroDivisionError</span><span class="p">:</span>
         <span class="k">return</span> <span class="mf">0.0</span>
</code></pre></div></div>

<p>Now we are safe! But why do we return <code class="language-plaintext highlighter-rouge">0</code>? Why not <code class="language-plaintext highlighter-rouge">1</code>? Why not <code class="language-plaintext highlighter-rouge">None</code>? And while <code class="language-plaintext highlighter-rouge">None</code> in most cases is as bad (or even worse) than the exceptions, turns out we should heavily rely on business logic and use-cases of this function.</p>

<p>What exactly do we divide? Arbitrary numbers? Some specific units? Money? Not all cases can be covered and easily restored. And sometimes when we will reuse this function for different use-cases we will find out that it requires different restore logic.</p>

<p>So, the sad conclusion is: <strong>all problems must be resolved individually</strong> depending on a specific usage context. There’s no silver bullet to resolve all <code class="language-plaintext highlighter-rouge">ZeroDivisionError</code>s once and for all. And again, I am not even covering complex IO flows with retry policies and expotential timeouts.</p>

<p>Maybe we should not even handle exceptions in-place at all? Maybe we should throw it further in the execution flow and someone will later handle it somehow.</p>


    
      <h3 id="execution-flow-is-unclear">
        
        <a class="anchor" href="#execution-flow-is-unclear">Execution flow is unclear</a>
        
      </h3>

<p>Ok, now we will hope that someone else will catch this exception and possibly handle it. For example, the system might notify the user to change the input, because we can not divide by <code class="language-plaintext highlighter-rouge">0</code>. Which is clearly not a responsibility of the <code class="language-plaintext highlighter-rouge">divide</code> function.</p>

<p>Now we just need to check where this exception is actually caught. By the way, how can we tell where exactly it will be handled? Can we navigate to this point in the code? Turns out, we can not do that.</p>

<p>There’s no way to tell which line of code will be executed after the exception is thrown. Different exception types might be handled by different <code class="language-plaintext highlighter-rouge">except</code> cases, some exceptions may be <a href="https://docs.python.org/3/library/contextlib.html#contextlib.suppress"><code class="language-plaintext highlighter-rouge">suppress</code>ed</a>. And you might also accidentally break your program in random spots by introducing new <code class="language-plaintext highlighter-rouge">except</code> cases in a different module. And remember that almost any line can raise.</p>

<p>We have two independent flows in our app: regular flow that goes from top to bottom and exceptional one that goes however it wants. How can we consciously read code like this?</p>

<p>Only with a debugger turned on. With “catch all exceptions” policy enabled.</p>

<p><img src="https://thepracticaldev.s3.amazonaws.com/i/838vfxwo8cdbankvb8x5.png" alt="IDE debugger"></p>

<p>Exceptions are just like notorious <code class="language-plaintext highlighter-rouge">goto</code> statements that torn the fabric of our programs.</p>


    
      <h3 id="exceptions-are-not-exceptional">
        
        <a class="anchor" href="#exceptions-are-not-exceptional">Exceptions are not exceptional</a>
        
      </h3>

<p>Let’s look at another example, a typical code to access remote HTTP API:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">import</span> <span class="nn">requests</span>

<span class="k">def</span> <span class="nf">fetch_user_profile</span><span class="p">(</span><span class="n">user_id</span><span class="p">:</span> <span class="nb">int</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="s">'UserProfile'</span><span class="p">:</span>
    <span class="s">"""Fetches UserProfile dict from foreign API."""</span>
    <span class="n">response</span> <span class="o">=</span> <span class="n">requests</span><span class="p">.</span><span class="n">get</span><span class="p">(</span><span class="s">'/api/users/{0}'</span><span class="p">.</span><span class="nb">format</span><span class="p">(</span><span class="n">user_id</span><span class="p">))</span>
    <span class="n">response</span><span class="p">.</span><span class="n">raise_for_status</span><span class="p">()</span>
    <span class="k">return</span> <span class="n">response</span><span class="p">.</span><span class="n">json</span><span class="p">()</span>
</code></pre></div></div>

<p>Literally, everything in this example can go wrong. Here’s an incomplete list of all possible errors that might occur:</p>

<ol>
  <li>Your network might be down, so request won’t happen at all</li>
  <li>The server might be down</li>
  <li>The server might be too busy and you will face a timeout</li>
  <li>The server might require an authentication</li>
  <li>API endpoint might not exist</li>
  <li>The user might not exist</li>
  <li>You might not have enough permissions to view it</li>
  <li>The server might fail with an internal error while processing your request</li>
  <li>The server might return an invalid or corrupted response</li>
  <li>The server might return invalid <code class="language-plaintext highlighter-rouge">json</code>, so the parsing will fail</li>
</ol>

<p>And the list goes on and on! There are so maybe potential problems with these three lines of code, that it is easier to say that it only <strong>accidentally</strong> works. And normally it fails with the exception.</p>


    
      <h2 id="how-to-be-safe">
        
        <a class="anchor" href="#how-to-be-safe">How to be safe?</a>
        
      </h2>

<p>Now we got that exceptions are harmful to your code. Let’s learn how to get rid off them. There are different patterns to write the exception-free code:</p>

<ol>
  <li>Write <a href="https://wemake-python-styleguide.readthedocs.io/en/latest/pages/violations/best_practices.html#wemake_python_styleguide.violations.best_practices.WrongKeywordViolation"><code class="language-plaintext highlighter-rouge">except Exception: pass</code></a> everywhere. That’s as bad as you can imagine. Don’t do it.</li>
  <li>Return <code class="language-plaintext highlighter-rouge">None</code>. That’s evil too! You either will end up with <code class="language-plaintext highlighter-rouge">if something is not None:</code> on almost every line and global pollution of your logic by type-checking conditionals, or will suffer from <code class="language-plaintext highlighter-rouge">TypeError</code> every day. Not a pleasant choice.</li>
  <li>Write special-case classes. For example, you will have <code class="language-plaintext highlighter-rouge">User</code> base class with multiple error-subclasses like <code class="language-plaintext highlighter-rouge">UserNotFound(User)</code> and <code class="language-plaintext highlighter-rouge">MissingUser(User)</code>. It might be used for some specific situations, like <a href="https://docs.djangoproject.com/en/2.1/ref/contrib/auth/#anonymoususer-object"><code class="language-plaintext highlighter-rouge">AnonymousUser</code></a> in <code class="language-plaintext highlighter-rouge">django</code>, but it is not possible to wrap all your possible errors in special-case classes. It will require too much work from a developer. And over-complicate your domain model.</li>
  <li>You can use container values, that wraps actual success or error value into a thin wrapper with utility methods to work with this value. That’s exactly why we have created <a href="https://github.com/dry-python/returns"><code class="language-plaintext highlighter-rouge">@dry-python/returns</code></a> project. So you can make your functions return something meaningful, typed, and safe.</li>
</ol>

<p>Let’s start with the same number dividing example, which returns <code class="language-plaintext highlighter-rouge">0</code> when the error happens. Maybe instead we can indicate that the result was not successful without any explicit numerical value?</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">from</span> <span class="nn">returns.result</span> <span class="kn">import</span> <span class="n">Result</span><span class="p">,</span> <span class="n">Success</span><span class="p">,</span> <span class="n">Failure</span>

<span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">first</span><span class="p">:</span> <span class="nb">float</span><span class="p">,</span> <span class="n">second</span><span class="p">:</span> <span class="nb">float</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Result</span><span class="p">[</span><span class="nb">float</span><span class="p">,</span> <span class="nb">ZeroDivisionError</span><span class="p">]:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">Success</span><span class="p">(</span><span class="n">first</span> <span class="o">/</span> <span class="n">second</span><span class="p">)</span>
    <span class="k">except</span> <span class="nb">ZeroDivisionError</span> <span class="k">as</span> <span class="n">exc</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">Failure</span><span class="p">(</span><span class="n">exc</span><span class="p">)</span>
</code></pre></div></div>

<p>Now we wrap our values in one of two wrappers: <code class="language-plaintext highlighter-rouge">Success</code> or <code class="language-plaintext highlighter-rouge">Failure</code>. These two classes inherit from <code class="language-plaintext highlighter-rouge">Result</code> base class. And we can specify types of wrapped values in a function return annotation, for example <code class="language-plaintext highlighter-rouge">Result[float, ZeroDivisionError]</code> returns either <code class="language-plaintext highlighter-rouge">Success[float]</code> or <code class="language-plaintext highlighter-rouge">Failure[ZeroDivisionError]</code>.</p>

<p>What does it mean to us? It means, that <strong>exceptions are not exceptional, they represent expectable problems</strong>. But, we also wrap them in <code class="language-plaintext highlighter-rouge">Failure</code> to solve the second problem: <strong>spotting potential exceptions is hard</strong>.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="mi">1</span> <span class="o">+</span> <span class="n">divide</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
<span class="c1"># =&gt; mypy error: Unsupported operand types for + ("int" and "Result[float, ZeroDivisionError]")
</span></code></pre></div></div>

<p>Now you can easily spot them! The rule is: if you see a <code class="language-plaintext highlighter-rouge">Result</code> it means that this function can throw an exception. And you even know its type in advance.</p>

<p>Moreover, <code class="language-plaintext highlighter-rouge">returns</code> library is fully typed and <a href="https://www.python.org/dev/peps/pep-0561/">PEP561 compatible</a>. It means that <code class="language-plaintext highlighter-rouge">mypy</code> will warn you if you try to return something that violates declared type contract.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">from</span> <span class="nn">returns.result</span> <span class="kn">import</span> <span class="n">Result</span><span class="p">,</span> <span class="n">Success</span><span class="p">,</span> <span class="n">Failure</span>

<span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">first</span><span class="p">:</span> <span class="nb">float</span><span class="p">,</span> <span class="n">second</span><span class="p">:</span> <span class="nb">float</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Result</span><span class="p">[</span><span class="nb">float</span><span class="p">,</span> <span class="nb">ZeroDivisionError</span><span class="p">]:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">Success</span><span class="p">(</span><span class="s">'Done'</span><span class="p">)</span>
        <span class="c1"># =&gt; error: incompatible type "str"; expected "float"
</span>    <span class="k">except</span> <span class="nb">ZeroDivisionError</span> <span class="k">as</span> <span class="n">exc</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">Failure</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
        <span class="c1"># =&gt; error: incompatible type "int"; expected "ZeroDivisionError"
</span></code></pre></div></div>


    
      <h3 id="how-to-work-with-wrapped-values">
        
        <a class="anchor" href="#how-to-work-with-wrapped-values">How to work with wrapped values?</a>
        
      </h3>

<p>There are two methods <a href="https://returns.readthedocs.io/en/latest/pages/container.html#working-with-containers">two work with these wrapped values</a>:</p>

<ul>
  <li>
<code class="language-plaintext highlighter-rouge">map</code> works with functions that return regular values</li>
  <li>
<code class="language-plaintext highlighter-rouge">bind</code> works with functions that return other containers</li>
</ul>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">Success</span><span class="p">(</span><span class="mi">4</span><span class="p">).</span><span class="n">bind</span><span class="p">(</span><span class="k">lambda</span> <span class="n">number</span><span class="p">:</span> <span class="n">Success</span><span class="p">(</span><span class="n">number</span> <span class="o">/</span> <span class="mi">2</span><span class="p">))</span>
<span class="c1"># =&gt; Success(2)
</span>
<span class="n">Success</span><span class="p">(</span><span class="mi">4</span><span class="p">).</span><span class="nb">map</span><span class="p">(</span><span class="k">lambda</span> <span class="n">number</span><span class="p">:</span> <span class="n">number</span> <span class="o">+</span> <span class="mi">1</span><span class="p">)</span>
<span class="c1"># =&gt; Success(5)
</span></code></pre></div></div>

<p>The thing is: you will be safe from failed scenarios. Since <code class="language-plaintext highlighter-rouge">.bind</code> and <code class="language-plaintext highlighter-rouge">.map</code> will  not execute for <code class="language-plaintext highlighter-rouge">Failure</code> containers:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">Failure</span><span class="p">(</span><span class="mi">4</span><span class="p">).</span><span class="n">bind</span><span class="p">(</span><span class="k">lambda</span> <span class="n">number</span><span class="p">:</span> <span class="n">Success</span><span class="p">(</span><span class="n">number</span> <span class="o">/</span> <span class="mi">2</span><span class="p">))</span>
<span class="c1"># =&gt; Failure(4)
</span>
<span class="n">Failure</span><span class="p">(</span><span class="mi">4</span><span class="p">).</span><span class="nb">map</span><span class="p">(</span><span class="k">lambda</span> <span class="n">number</span><span class="p">:</span> <span class="n">number</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span>
<span class="c1"># =&gt; Failure(4)
</span></code></pre></div></div>

<p>Now you can just concentrate on correct execution flow and be sure that failed state won’t break your program in random places.</p>

<p>And you can always <a href="https://returns.readthedocs.io/en/latest/pages/railway.html">take care of a failed state and even fix it</a> and return to the right track if you want to.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">Failure</span><span class="p">(</span><span class="mi">4</span><span class="p">).</span><span class="n">rescue</span><span class="p">(</span><span class="k">lambda</span> <span class="n">number</span><span class="p">:</span> <span class="n">Success</span><span class="p">(</span><span class="n">number</span> <span class="o">+</span> <span class="mi">1</span><span class="p">))</span>
<span class="c1"># =&gt; Success(5)
</span>
<span class="n">Failure</span><span class="p">(</span><span class="mi">4</span><span class="p">).</span><span class="n">fix</span><span class="p">(</span><span class="k">lambda</span> <span class="n">number</span><span class="p">:</span> <span class="n">number</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span>
<span class="c1"># =&gt; Success(2)
</span></code></pre></div></div>

<p>It means that “<strong>all problems must be resolved individually</strong>” practice is the only way to go and “<strong>execution flow is now clear</strong>”. Enjoy your railway programming!</p>


    
      <h3 id="but-how-to-unwrap-values-from-containers">
        
        <a class="anchor" href="#but-how-to-unwrap-values-from-containers">But how to unwrap values from containers?</a>
        
      </h3>

<p>Yes, indeed, you really need raw values when dealing with functions that actually accept these raw values. You can use <a href="https://returns.readthedocs.io/en/latest/pages/railway.html#unwrapping-values"><code class="language-plaintext highlighter-rouge">.unwrap()</code> or <code class="language-plaintext highlighter-rouge">.value_or()</code></a> methods:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">Success</span><span class="p">(</span><span class="mi">1</span><span class="p">).</span><span class="n">unwrap</span><span class="p">()</span>
<span class="c1"># =&gt; 1
</span>
<span class="n">Success</span><span class="p">(</span><span class="mi">0</span><span class="p">).</span><span class="n">value_or</span><span class="p">(</span><span class="bp">None</span><span class="p">)</span>
<span class="c1"># =&gt; 0
</span>
<span class="n">Failure</span><span class="p">(</span><span class="mi">0</span><span class="p">).</span><span class="n">value_or</span><span class="p">(</span><span class="bp">None</span><span class="p">)</span>
<span class="c1"># =&gt; None
</span>
<span class="n">Failure</span><span class="p">(</span><span class="mi">1</span><span class="p">).</span><span class="n">unwrap</span><span class="p">()</span>
<span class="c1"># =&gt; Raises UnwrapFailedError()
</span></code></pre></div></div>

<p><em>Wait, what?</em> You have promised to save me from exceptions and now you are telling me that all my <code class="language-plaintext highlighter-rouge">.unwrap()</code> calls can result in one more exception!</p>


    
      <h3 id="how-not-to-care-about-these-unwrapfailederrors">
        
        <a class="anchor" href="#how-not-to-care-about-these-unwrapfailederrors">How not to care about these UnwrapFailedErrors?</a>
        
      </h3>

<p>Ok, let’s see how to live with these new exceptions. Consider this example: we need to validate the user’s input, then create two models in a database. And every step might fail with the exception, so we have wrapped all methods into the <code class="language-plaintext highlighter-rouge">Result</code> wrapper:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">from</span> <span class="nn">returns.result</span> <span class="kn">import</span> <span class="n">Result</span><span class="p">,</span> <span class="n">Success</span><span class="p">,</span> <span class="n">Failure</span>

<span class="k">class</span> <span class="nc">CreateAccountAndUser</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="s">"""Creates new Account-User pair."""</span>

    <span class="c1"># TODO: we need to create a pipeline of these methods somehow...
</span>
    <span class="k">def</span> <span class="nf">_validate_user</span><span class="p">(</span>
        <span class="bp">self</span><span class="p">,</span> <span class="n">username</span><span class="p">:</span> <span class="nb">str</span><span class="p">,</span> <span class="n">email</span><span class="p">:</span> <span class="nb">str</span><span class="p">,</span>
    <span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Result</span><span class="p">[</span><span class="s">'UserSchema'</span><span class="p">,</span> <span class="nb">str</span><span class="p">]:</span>
        <span class="s">"""Returns an UserSchema for valid input, otherwise a Failure."""</span>

    <span class="k">def</span> <span class="nf">_create_account</span><span class="p">(</span>
        <span class="bp">self</span><span class="p">,</span> <span class="n">user_schema</span><span class="p">:</span> <span class="s">'UserSchema'</span><span class="p">,</span>
    <span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Result</span><span class="p">[</span><span class="s">'Account'</span><span class="p">,</span> <span class="nb">str</span><span class="p">]:</span>
        <span class="s">"""Creates an Account for valid UserSchema's. Or returns a Failure."""</span>

    <span class="k">def</span> <span class="nf">_create_user</span><span class="p">(</span>
        <span class="bp">self</span><span class="p">,</span> <span class="n">account</span><span class="p">:</span> <span class="s">'Account'</span><span class="p">,</span>
    <span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Result</span><span class="p">[</span><span class="s">'User'</span><span class="p">,</span> <span class="nb">str</span><span class="p">]:</span>
        <span class="s">"""Create an User instance. If user already exists returns Failure."""</span>
</code></pre></div></div>

<p>First of all, you can not unwrap any values while writing your own business logic:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">CreateAccountAndUser</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="s">"""Creates new Account-User pair."""</span>

    <span class="k">def</span> <span class="nf">__call__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">username</span><span class="p">:</span> <span class="nb">str</span><span class="p">,</span> <span class="n">email</span><span class="p">:</span> <span class="nb">str</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Result</span><span class="p">[</span><span class="s">'User'</span><span class="p">,</span> <span class="nb">str</span><span class="p">]:</span>
        <span class="s">"""Can return a Success(user) or Failure(str_reason)."""</span>
        <span class="k">return</span> <span class="bp">self</span><span class="p">.</span><span class="n">_validate_user</span><span class="p">(</span>
            <span class="n">username</span><span class="p">,</span> <span class="n">email</span><span class="p">,</span>
        <span class="p">).</span><span class="n">bind</span><span class="p">(</span>
            <span class="bp">self</span><span class="p">.</span><span class="n">_create_account</span><span class="p">,</span>
        <span class="p">).</span><span class="n">bind</span><span class="p">(</span>
            <span class="bp">self</span><span class="p">.</span><span class="n">_create_user</span><span class="p">,</span>
        <span class="p">)</span>

   <span class="c1"># ...
</span></code></pre></div></div>

<p>And this will work without any problems. It won’t raise any exceptions, because <code class="language-plaintext highlighter-rouge">.unwrap()</code> is not used. But, is it easy to read code like this? <strong>No</strong>, it is not. What alternative can we provide? <code class="language-plaintext highlighter-rouge">@pipeline</code>!</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">from</span> <span class="nn">result.functions</span> <span class="kn">import</span> <span class="n">pipeline</span>

<span class="k">class</span> <span class="nc">CreateAccountAndUser</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="s">"""Creates new Account-User pair."""</span>

    <span class="o">@</span><span class="n">pipeline</span>
    <span class="k">def</span> <span class="nf">__call__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">username</span><span class="p">:</span> <span class="nb">str</span><span class="p">,</span> <span class="n">email</span><span class="p">:</span> <span class="nb">str</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Result</span><span class="p">[</span><span class="s">'User'</span><span class="p">,</span> <span class="nb">str</span><span class="p">]:</span>
        <span class="s">"""Can return a Success(user) or Failure(str_reason)."""</span>
        <span class="n">user_schema</span> <span class="o">=</span> <span class="bp">self</span><span class="p">.</span><span class="n">_validate_user</span><span class="p">(</span><span class="n">username</span><span class="p">,</span> <span class="n">email</span><span class="p">).</span><span class="n">unwrap</span><span class="p">()</span>
        <span class="n">account</span> <span class="o">=</span> <span class="bp">self</span><span class="p">.</span><span class="n">_create_account</span><span class="p">(</span><span class="n">user_schema</span><span class="p">).</span><span class="n">unwrap</span><span class="p">()</span>
        <span class="k">return</span> <span class="bp">self</span><span class="p">.</span><span class="n">_create_user</span><span class="p">(</span><span class="n">account</span><span class="p">)</span>

   <span class="c1"># ...
</span></code></pre></div></div>

<p>Now it is perfectly readable. That’s how <code class="language-plaintext highlighter-rouge">.unwrap()</code> and <code class="language-plaintext highlighter-rouge">@pipeline</code> synergy works: whenever any <code class="language-plaintext highlighter-rouge">.unwrap()</code> method will fail on <code class="language-plaintext highlighter-rouge">Failure[str]</code> instance <code class="language-plaintext highlighter-rouge">@pipeline</code> decorator will catch it and return <code class="language-plaintext highlighter-rouge">Failure[str]</code> as a result value. That’s how we can eliminate all the exceptions from our code and make it truly type-safe.</p>


    
      <h2 id="wrapping-all-together">
        
        <a class="anchor" href="#wrapping-all-together">Wrapping all together</a>
        
      </h2>

<p>Now, let’s solve this <code class="language-plaintext highlighter-rouge">requests</code> example with all the new tools we have. Remember, that each line could raise an exception? And there’s no way to make them return <code class="language-plaintext highlighter-rouge">Result</code> container. But you can use <a href="https://returns.readthedocs.io/en/latest/pages/result.html#safe"><code class="language-plaintext highlighter-rouge">@safe</code> decorator</a> to wrap unsafe functions and make them safe. These two examples are identical:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">from</span> <span class="nn">returns.functions</span> <span class="kn">import</span> <span class="n">safe</span>

<span class="o">@</span><span class="n">safe</span>
<span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">first</span><span class="p">:</span> <span class="nb">float</span><span class="p">,</span> <span class="n">second</span><span class="p">:</span> <span class="nb">float</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="nb">float</span><span class="p">:</span>
     <span class="k">return</span> <span class="n">first</span> <span class="o">/</span> <span class="n">second</span>


<span class="c1"># is the same as:
</span>
<span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">first</span><span class="p">:</span> <span class="nb">float</span><span class="p">,</span> <span class="n">second</span><span class="p">:</span> <span class="nb">float</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Result</span><span class="p">[</span><span class="nb">float</span><span class="p">,</span> <span class="nb">ZeroDivisionError</span><span class="p">]:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">Success</span><span class="p">(</span><span class="n">first</span> <span class="o">/</span> <span class="n">second</span><span class="p">)</span>
    <span class="k">except</span> <span class="nb">ZeroDivisionError</span> <span class="k">as</span> <span class="n">exc</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">Failure</span><span class="p">(</span><span class="n">exc</span><span class="p">)</span>
</code></pre></div></div>

<p>And we can see that the first one with <code class="language-plaintext highlighter-rouge">@safe</code> is way more readable and simple.</p>

<p>That’s the last thing we needed to solve our <code class="language-plaintext highlighter-rouge">requests</code> problem. That’s how our result code will look like in the end:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">import</span> <span class="nn">requests</span>
<span class="kn">from</span> <span class="nn">returns.functions</span> <span class="kn">import</span> <span class="n">pipeline</span><span class="p">,</span> <span class="n">safe</span>
<span class="kn">from</span> <span class="nn">returns.result</span> <span class="kn">import</span> <span class="n">Result</span>

<span class="k">class</span> <span class="nc">FetchUserProfile</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="s">"""Single responsibility callable object that fetches user profile."""</span>

    <span class="c1">#: You can later use dependency injection to replace `requests`
</span>    <span class="c1">#: with any other http library (or even a custom service).
</span>    <span class="n">_http</span> <span class="o">=</span> <span class="n">requests</span>

    <span class="o">@</span><span class="n">pipeline</span>
    <span class="k">def</span> <span class="nf">__call__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">user_id</span><span class="p">:</span> <span class="nb">int</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Result</span><span class="p">[</span><span class="s">'UserProfile'</span><span class="p">,</span> <span class="nb">Exception</span><span class="p">]:</span>
        <span class="s">"""Fetches UserProfile dict from foreign API."""</span>
        <span class="n">response</span> <span class="o">=</span> <span class="bp">self</span><span class="p">.</span><span class="n">_make_request</span><span class="p">(</span><span class="n">user_id</span><span class="p">).</span><span class="n">unwrap</span><span class="p">()</span>
        <span class="k">return</span> <span class="bp">self</span><span class="p">.</span><span class="n">_parse_json</span><span class="p">(</span><span class="n">response</span><span class="p">)</span>

    <span class="o">@</span><span class="n">safe</span>
    <span class="k">def</span> <span class="nf">_make_request</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">user_id</span><span class="p">:</span> <span class="nb">int</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">requests</span><span class="p">.</span><span class="n">Response</span><span class="p">:</span>
        <span class="n">response</span> <span class="o">=</span> <span class="bp">self</span><span class="p">.</span><span class="n">_http</span><span class="p">.</span><span class="n">get</span><span class="p">(</span><span class="s">'/api/users/{0}'</span><span class="p">.</span><span class="nb">format</span><span class="p">(</span><span class="n">user_id</span><span class="p">))</span>
        <span class="n">response</span><span class="p">.</span><span class="n">raise_for_status</span><span class="p">()</span>
        <span class="k">return</span> <span class="n">response</span>

    <span class="o">@</span><span class="n">safe</span>
    <span class="k">def</span> <span class="nf">_parse_json</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">response</span><span class="p">:</span> <span class="n">requests</span><span class="p">.</span><span class="n">Response</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="s">'UserProfile'</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">response</span><span class="p">.</span><span class="n">json</span><span class="p">()</span>
</code></pre></div></div>

<p>Things to recap:</p>
<ol>
  <li>We use <code class="language-plaintext highlighter-rouge">@safe</code> for all methods that can raise an exception, it will change the return type of the function to <code class="language-plaintext highlighter-rouge">Result[OldReturnType, Exception]</code>
</li>
  <li>We use <code class="language-plaintext highlighter-rouge">Result</code> as a container for wrapping values and errors in a simple abstraction</li>
  <li>We use <code class="language-plaintext highlighter-rouge">.unwrap()</code> to unwrap raw value from the container</li>
  <li>We use <code class="language-plaintext highlighter-rouge">@pipeline</code> to make sequences of <code class="language-plaintext highlighter-rouge">.unwrap</code> calls readable</li>
</ol>

<p>This is a perfectly readable and safe way to do the exact same thing as we previously did with the unsafe function. It eliminates all the problems we had with exceptions:</p>

<ol>
  <li>“Exceptions are hard to notice”. Now, they are wrapped with a typed <code class="language-plaintext highlighter-rouge">Result</code> container, which makes them crystal clear.</li>
  <li>“Restoring normal behavior in-place is impossible”. We now can safely delegate the restoration process to the caller. We provide <code class="language-plaintext highlighter-rouge">.fix()</code> and <code class="language-plaintext highlighter-rouge">.rescue()</code> methods for this specific use-case.</li>
  <li>“Execution flow is unclear”. Now it is the same as a regular business flow. From top to bottom.</li>
  <li>“Exceptions are not exceptional”. And we know it! We expect things to go wrong and are ready for it.</li>
</ol>


    
      <h2 id="use-cases-and-limitations">
        
        <a class="anchor" href="#use-cases-and-limitations">Use-cases and limitations</a>
        
      </h2>

<p>Obviously, you can not write all your code this way. It is just <strong>too</strong> safe for the most situations and incompatible with other libraries/frameworks. But, you should definitely write the most important parts of your business logic as I have shown above. It will increase the maintainability and correctness of your system.</p>

    </div>

    <hr>

    <div class="post-subscribe">
      <h2>
        <a href="https://sobolevn.me/subscribe">
          Subscribe to my blog if you want more
        </a>
      </h2>
    </div>

    
    
    <div class="post-republish">
      <h4>Republished as:</h4>
      <ul>
      
        <li>
          <a class="c-article__repost" href="https://dev.to/wemake-services/python-exceptions-considered-an-anti-pattern-17o9" target="_blank">
            
            dev.to <img class="emoji" title=":us:" alt=":us:" src="https://github.githubassets.com/images/icons/emoji/unicode/1f1fa-1f1f8.png" height="20" width="20">
          </a>
        </li>
      
      </ul>
    </div>
    
  </div>

  <!-- Disqus comments view -->
  
</article>

  </div>
  <footer class="c-page__footer">
  <p>
    <i class="far fa-copyright"></i>
    <a href="https://sobolevn.me/about/">imrishi</a>
    2023,
    content licensed
    <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">
      CC BY-NC
    </a>,
    <a href="https://github.com/sobolevn/sobolevn.github.io" target="_blank">
      source code
    </a>
  </p>

  <p>
    <a href="mailto:r@rishi.im" alt="email">
      <i class="far fa-2x fa-envelope"></i>
    </a>
    <a href="https://github.com/sobolevn" alt="github">
      <i class="fab fa-2x fa-github"></i>
    </a>
    <a href="https://dev.to/sobolevn" alt="practicaldev">
      <i class="fab fa-2x fa-dev"></i>
    </a>
    <a href="https://medium.com/@sobolevn" alt="medium">
      <i class="fab fa-2x fa-medium"></i>
    </a>
    <a href="https://stackoverflow.com/users/4842742/sobolevn" alt="stackoverflow">
      <i class="fab fa-2x fa-stack-overflow"></i>
    </a>
  </p>
</footer>

</div>

    </main>

    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-66588818-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-66588818-1');
</script>

  </body>
</html>
